.TH rxc 1 rxc\-VERSION
.SH NAME
rxc \- REXos terminal client
.SH SYNOPSIS
.B rxc
.RB command
.SH DESCRIPTION
rxc is a simple command line tool which allows to talk the REXos cloud
services. One of the most important features is to get a valid access token
which can be used with lot of other tools and SDKs. The first thing you need
is to use the login command in order to get a valid token.
.P
You also need a config.yml file which contains your REXos instances information.
.SH SEE ALSO
.BR rxi (1)
